### ISSUE TITLE
Forge not defined

### ISSUE THREAD

**Issue by marcus433** [whiteout-io/imap-client#32]
When using the imap-client, browserbox, tls stack with nodejs I get a forge not defined error. Is this common? Also to note Im running node inside atom-shell

**Comment by flxw** [comment]
I was about to open a new issue, but I saw that this one might match the one I am having.
When doing `npm install && grunt`, the tests fail because forge.min.js is missing.
You can fix that by running `npm install && npm test` instead, which runs the pretest hook which gets you forge.min.js. The tests will all pass (nicely done!)

But now, if you *require* imap-client inside a Chrome extension, the following will happen.
Renaming `forge.min.js` to `forge.js` inside `node_modules/imap-client/test/lib/` will fix this problem. But then the tests won't run anymore.

One of the poses a problem, so my suggestion is to fix the tests by `require`-ing *forge.js* instead of *forge.min.js*. If you want, I can give you a pull request for this.

![badforge](https://cloud.githubusercontent.com/assets/942398/5789351/5f03f8ea-9e67-11e4-8477-24f705146dfa.png)

**Comment by felixhammerl** [comment]
hi, sorry for taking so long to answer this.
yes, you obviously need to build forge, as it is a dependency.
if you use require.js, it is generally a bad idea to mess around with the file names, instead [you should configure your paths in the require config](http://requirejs.org/docs/api.html#config), like so: https://github.com/whiteout-io/imap-client/blob/master/test/unit.js#L7
