### ISSUE TITLE
IMAP Authentication type: Cram-MD5 (Encrypted password)

### ISSUE THREAD

**Issue by engeuio** [whiteout-io/imap-client#49]
I was not able to log in using your client.
Do you support Cram-MD5 Authentication?
If you do not, do you have an ETA for it?

**Comment by felixhammerl** [comment]
nope, we only support PLAIN

**Comment by felixhammerl** [comment]
also, it's kind of irrelevant when you use TLS

**Comment by andris9** [comment]
CRAM-MD5 should die, it's like the worst authentication scheme ever. In order to support this, the server must either store user passwords in plain text or as partially calculated MD5 of the password which isn't secure either.

**Comment by toddInPortland** [comment]
> CRAM-MD5 should die

Perhaps. But given that it is much harder to change an established mail server's authentication method (like mine), it seems a bit restrictive to block the use of imaplib's login_cram_md5(). Especially since imapclient uses it as its underpinnings.

Below is the missing method, that you can attach by calling install(). You should not consider this as a supported feature of imapclient, but it will allow you to get connected to the server that insists on cram_md5.

Place the code block below in a file named cram_md5_addon.py in your project.
```
from imapclient import IMAPClient, exceptions
from imapclient.util import to_unicode, logger

def login_cram_md5(self, username, password):
    """Login using *username* and *password*, returning the
    server response.
    """
    try:
        rv = self._command_and_check(
            'login_cram_md5',
            to_unicode(username),
            to_unicode(password),
            unpack=True,
        )
    except exceptions.IMAPClientError as e:
        raise exceptions.LoginError(str(e))

    logger.info('Logged in as %s', username)
    return rv

def install():
    IMAPClient.login_cram_md5 = login_cram_md5
```
 Then somewhere in your startup, attach the missing method to the class by adding the lines
```
import cram_md5_addon
cram_md5_addon.install()

```
Then you can call
```
    server = IMAPClient('host.com')
    status = server.login_cram_md5('username', 'password')
```
