### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by guettli** [whiteout-io/imap-client#50]
On https://whiteout.io/ I read:

> As of January 1st 2016 the Whiteout Mail service is no longer available.

What is the status of this imap-client module on github?

**Comment by tanx** [comment]
Repos under this github org are not longer maintained. Please use the new emailjs.org repos.

**Comment by felixhammerl** [comment]
Although not particularly rocket science, this part might still be interesting to you: https://github.com/whiteout-io/imap-client/blob/master/src/imap-client.js#L128-L392

The rest of the overhead functionality the imap client offered has since been introduces to the https://github.com/emailjs/emailjs-imap-client
